server:
  port: 10000
spring:
  application:
    name: SCW-WEBUI
  redis:
    host: 139.224.30.125
    password: dyq*1010A
    port: 8989
  session: 
    store-type: redis
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #开发的时候禁用缓存

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-WEBUI
    prefer-ip-address: true
   
   
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0  
  OkToRetryOnAllOperations: false 
  
  
alipay:
  app_id: 2021000117601132
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCfrdJPIggJPOgw3Co6u83HDcVQTZFZzNZ9uumL/4L+d7ewUyAnznGrKJXhUNcfd/B6LGg0hqYfReHmUVdVEE0j1E9mdu+ziTMe8bZn+Awdww2oqp9ObJs0tGOKpabCvKw0YZiNJlGEHyHJDPeWCpmEvz5vyqZ+MxM2yaayOEMq5V4ylPTVyjT+iqCDMLj80/1LwVE3Eo6iaYRvCmYRDP83sIcjfluVXiOj3XcUYjBovyHJaPtzWInuDDhl2Eqs1LkPmP4jd+wMDg5HXaRiOScvs3/0lVwtWx+UjfF1EEvgYjqbPNMeHBulV5n8ecsknkwOPlubLXhIhd1Lsznz96fzAgMBAAECggEARmChQfl420F6ARb4kdx2bNY38hXOC2tJ2i6IgwjB3pA7aL6qfIDz/oEr1hwARMFjPyXVY9k43K27S/zr5fUCWtlXiYzARzwgSPI1+AsOpAt1OLLC9hjOK2OaP+CU6F2p9IhTaVrLMNVb2bYaZYoUcbqstS73RMYUIOCt1P0RNZUiM9ilYquS6/mex/u4yDls8pAIgyZY7hFqpiVGGsjWdn2ijX4UaLhqs17THh9VJxAP3XWyTDLL2VnagELTdkQcNYr5LKXq9ms95zbJheWfIHnUXYzZPitZ3ytINaVzhaANiFJiH0u3pVIDzvutr7v26HSV9bpsQRhPQzwMydFBcQKBgQDOtLaNuq6eiiMVnso7xf8o1Ebv3kWY2XMyARCTsQVyKQmGcKzsSuWXcpir7Nm8qHbHHCt+qn6W7GlYczG08F2e7zFIx4bJXsxFLiXKFIxv0qQfuMcx2sHmCq4mi19CbwPlwhT8AT561oQc2m4o0goJ10Cu7+lAFaHmFGi9sa0S+QKBgQDFwiPE8RJ6/juctbT/TUUcQUPPz3J/W4WpVSJiYFKN2hq205Y9zZ1A2i3KW3StTVuRujXSxY/9RKQgMVoFsHyTNBQpdttzqVQ3mFJEGcOt7ID2S0TW0V2j54sEajaI42Qrqy91UwAvOQpEqOD0PvpVeonMqSLTLUH17RJZQJkhSwKBgBOG0MP8wagqZnwRXwtcfekufHEGb06sJAyyOw2oqFoLdGHl3QAJZzzyT2fWXQ9MXsQabiVuF71MIfuADk8Icd+kuuQkLSByuxtB68H2RPn/TQ/OFcso3i5MDf2IJvyQni6jMfZIa82Q3DQZklR62wXo9qxP75nlMUEZ5ncdBLuJAoGAeqWF042DXZ4w0GbtIu0EMJrVeJt6sjvLsJIpKgP9Dxa2PK8K3beYkHD/tyFzQkvYv49R9C8stvGMLJ8O6rpi+FRzMKgTQC9DGNuyIaQs9L/Z12YlAmmEfrOKRymsOsd0B5U6cLQSSDdDBAQMx84LKVo+/hvjij7mSqRGHe5vSfMCgYBYt2oVlGJKkBL1C2Jo9OqNlqaWVz6XKbywXGlogcY/tuNI+p7wMdNCEM4yK60BKGcw+Z/11i0GImz4gq+8uu7q8Fy5Ek8NviVtN3Xq+p71u5Oyf6G5jNNUc7I/OGoHsNWaebZmWCUYVVv2xpmBe1RkSYNfpSrsDYiMeQa/u4qzoA==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn63STyIICTzoMNwqOrvNxw3FUE2RWczWfbrpi/+C/ne3sFMgJ85xqyiV4VDXH3fweixoNIamH0Xh5lFXVRBNI9RPZnbvs4kzHvG2Z/gMHcMNqKqfTmybNLRjiqWmwrysNGGYjSZRhB8hyQz3lgqZhL8+b8qmfjMTNsmmsjhDKuVeMpT01co0/oqggzC4/NP9S8FRNxKOommEbwpmEQz/N7CHI35blV4jo913FGIwaL8hyWj7c1iJ7gw4ZdhKrNS5D5j+I3fsDA4OR12kYjknL7N/9JVcLVsflI3xdRBL4GI6mzzTHhwbpVeZ/HnLJJ5MDj5bmy14SIXdS7M58/en8wIDAQAB
  notify_url: http://localhost:10000/order/updateOrderStatus
  return_url: http://localhost:10000/member/minecrowdfunding
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do 
  
  
  
  
  
  
  