spring:
  datasource:
    username: root
    password: 769800
    url: jdbc:mysql://139.224.30.125:3306/DBzc?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: SCW-PROJECT 
  redis:
    host: 139.224.30.125
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB #单个文件大小
      max-request-size: 10MB #总文件大小

feign:
  hystrix:
    enabled: true
    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://139.224.30.125:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true
    
server:
  port: 8001
  
swagger2: 
  enable: true
  
oss:
  endpoint: oss-cn-chengdu.aliyuncs.com
  accessKeyId: 
  accessKeySecret: 
  bucketName: dyq-scw
    
  
